// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW4aLmC54M2_eMfzEyTCFrIagiF5LIigw',
    appId: '1:547341101992:web:1c093af40b78b2dc2f4b9d',
    messagingSenderId: '547341101992',
    projectId: 'camera-app-91af2',
    authDomain: 'camera-app-91af2.firebaseapp.com',
    storageBucket: 'camera-app-91af2.appspot.com',
    measurementId: 'G-T397XFK17P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLMaUCOfXWE6wyIwxN97_d7Ia3q4-pPg',
    appId: '1:547341101992:android:d8c16c8b088f6cf02f4b9d',
    messagingSenderId: '547341101992',
    projectId: 'camera-app-91af2',
    storageBucket: 'camera-app-91af2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdwta4-l1RTN7R67jEFS6Hbo-pk-YU9w',
    appId: '1:547341101992:ios:08b46b95879d9ce72f4b9d',
    messagingSenderId: '547341101992',
    projectId: 'camera-app-91af2',
    storageBucket: 'camera-app-91af2.appspot.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNdwta4-l1RTN7R67jEFS6Hbo-pk-YU9w',
    appId: '1:547341101992:ios:0a69a521e644c9c82f4b9d',
    messagingSenderId: '547341101992',
    projectId: 'camera-app-91af2',
    storageBucket: 'camera-app-91af2.appspot.com',
    iosBundleId: 'com.example.cameraApp.RunnerTests',
  );
}
